services:
  postgres:
    container_name: postgres_flash_ticket
    image: pgvector/pgvector:pg14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'ticket@7#'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_flash_ticket
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - backend
    restart: unless-stopped

  rabbitmq:
    container_name: rabbitmq_flash_ticket
    image: rabbitmq:4-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    restart: unless-stopped

  keycloak:
    container_name: keycloak-flash-ticket
    image: quay.io/keycloak/keycloak:26.0.0
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

      KC_HTTP_RELATIVE_PATH: /auth
      KC_HOSTNAME: 15.134.248.39/auth
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
#      KC_PROXY: "edge"
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME_DEBUG: "true"
      KC_DB_URL_PROPERTIES: "?sslmode=disable"

      
      KC_SPI_EVENTS_LISTENER_RABBITMQ_HOST: rabbitmq
      KC_SPI_EVENTS_LISTENER_RABBITMQ_PORT: 5672
      KC_SPI_EVENTS_LISTENER_RABBITMQ_USERNAME: guest
      KC_SPI_EVENTS_LISTENER_RABBITMQ_PASSWORD: guest
      KC_SPI_EVENTS_LISTENER_RABBITMQ_EXCHANGE: keycloak.events  
      
    command: start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data/
      - ./keycloak-rabbitmq-spi.jar:/opt/keycloak/providers/keycloak-rabbitmq-spi.jar 
      - /home/ubuntu/flash-ticket:/opt/keycloak/themes/flash-ticket
      #File JAR phải nằm cùng thư mục với docker-compose.yml:
    networks:
      - backend
    restart: unless-stopped

  mongo:
    container_name: mongodb_flash_ticket
    image: mongodb/mongodb-community-server:latest
    ports:
      - "27018:27017"
    networks:
      - backend
    restart: unless-stopped


  redis:
    image: redis:7-alpine
    container_name: redis_flash_ticket
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  keycloak_data:
  redis_data:
