spring:
  # 1. Ghi đè Database trỏ vào container Postgres nội bộ của EC2
  datasource:
    url: jdbc:postgresql://postgres_flash_ticket:5432/flash-ticket?currentSchema=discovery_schema,public
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:ticket@7#}

  # 2. Ghi đè RabbitMQ trỏ về container RabbitMQ nội bộ
  rabbitmq:
    host: rabbitmq_flash_ticket

  # 3. Ghi đè Keycloak Issuer URI để xác thực token (trỏ về IP Public)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://15.134.248.39/realms/flash-ticket
          jwk-set-uri: http://keycloak-flash-ticket:8080/realms/flash-ticket/protocol/openid-connect/certs

# 4. Lưu vết API Key của Gemini để chạy AI chatbot
langchain4j:
  google-ai-gemini:
    chat-model:
      api-key: AIzaSyD3ZSe4oZYM6qmEolIJOP-aJMB-RUWJGGQ
