server:
  port: ${SERVER_PORT:8082}

spring:
  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: ${MONGO_DATABASE:ticketbox_users}
  
  # RabbitMQ Configuration
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

# Management & Monitoring
management:
  endpoints:
    web:
      exposure:
        include: "*"

# Keycloak Admin Configuration dùng Keycloak Admin API.

# Cách 1 Dùng Service Account + client-secret
keycloak:
  admin:
    server-url: ${KEYCLOAK_SERVER_URL}
    realm: ${KEYCLOAK_REALM:flash-ticket}
    client-id: ${KEYCLOAK_CLIENT_ID:user-service}
    client-secret: ${KEYCLOAK_CLIENT_SECRET}

#Cách 2 — Dùng admin-cli + username/password (đơn giản hơn):

#keycloak:
#  admin:
#    server-url: ${KEYCLOAK_SERVER_URL}
#    realm: ${KEYCLOAK_REALM:flash-ticket}
#    client-id: admin-cli
#    username: ${KEYCLOAK_ADMIN_USERNAME}
#    password: ${KEYCLOAK_ADMIN_PASSWORD}



# Logging
logging:
  level:
    com.flashticket.user: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}