spring:
  # 1. Ghi đè MongoDB trỏ về container MongoDB nội bộ của EC2
  data:
    mongodb:
      uri: mongodb://mongodb_flash_ticket:27017/ticketbox_users

  # 2. Ghi đè RabbitMQ trỏ về container RabbitMQ nội bộ
  rabbitmq:
    host: rabbitmq_flash_ticket

  # 3. Ghi đè Keycloak Issuer URI để xác thực token (trỏ về IP Public)
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://15.134.248.39:9090/auth/realms/flash-ticket

# 4. Ghi đè cấu hình Keycloak Admin API (Dùng container nội bộ keycloak:8080 để bypass internet)
keycloak:
  admin:
    server-url: http://keycloak-flash-ticket:8080/auth
    realm: flash-ticket
    client-id: flash-ticket-user-management-client
    client-secret: XS9KSU9iwnXL4bg47bHX3TQPi9DiPROD
