server:
  port: 8888

spring:
  application:
    name: configserver
  rabbitmq:
    host: 13.239.118.235  # AWS EC2
    port: 5672
    username: guest
    password: guest
  #  cloud:
  #    config:
  #      server:
  #        git:
  #          uri: https://github.com/levanminh04/spring-cloud-config.git
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:/D:/Ky_2_nam_4/TMDT/flash-ticket-system/configserver/src/main/resources/config/
#   test/dev thì dùng native cho tiện

management:
  endpoints:
    web:
      exposure:
        include: "*"