server:
  port: 8888

spring:
  application:
    name: configserver
  profiles:
    active: local,native

---
# ------------------------------------------------------------------------------
# PROFILE: LOCAL (Môi trường phát triển của Developer)
# ------------------------------------------------------------------------------
spring:
  config:
    activate:
      on-profile: local
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enabled: false
    config:
      server:
        native:
          search-locations: file:./src/main/resources/config/

---
# ------------------------------------------------------------------------------
# PROFILE: PROD (Môi trường AWS EC2 Production)
# ------------------------------------------------------------------------------
spring:
  config:
    activate:
      on-profile: prod
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/

---
# ------------------------------------------------------------------------------
# Cấu hình chung cho Actuator Endpoints (Tất cả môi trường)
# ------------------------------------------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: "*"
